---

root: true

extends:
  - 'eslint:recommended'
  - 'plugin:vue/strongly-recommended'

parserOptions:
  ecmaVersion: 6
  sourceType: module

env:
  browser: true
  node: true
  es6: true
  commonjs: true
